task/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from project import views as project_views

urlpatterns = [
    # user app url
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', user_view.register, name='register'),
    path('verify-otp/', user_view.verify_otp, name='verify_otp'),
    path('profile/', user_view.profile, name='profile'),

    # project app url
    path('', project_views.home, name='home'),
    path('tasks/', project_views.task_list, name='task'),
    path('task_detail/<int:id>/', project_views.task_detail, name='task_detail'),
    path('task/new/', project_views.TaskCreateView.as_view(template_name='tasks/task_form.html'), name='task-create'),
    path('task/<int:pk>/update/', project_views.TaskUpdateView.as_view(template_name='tasks/task_form.html'), name='task_update'),
    path('task/<int:pk>/delete/', project_views.TaskCreateView.as_view(template_name='tasks/task_form.html'), name='task-delete'),
    # path('add_team/', project_views.add_team, name='add_team'),
    path('add_team/', project_views.add_team, name='add_team'),
    path('team/', project_views.team, name='team'),

    # admin dashboard
    path('admin_home', project_views.admin_home, name='admin_home'),


    # Team member dashboard
    path('TM_dashboard', project_views.tm_dashboard, name='TM_dashboard'),

    # password reset
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-comfirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
        name='password_reset_complete'),

    #Chart
    # path('task-status-data/', project_views.task_status_data, name='task_status_data'),
    # path('task-incident-data/', project_views.task_incident_data, name='task_incident_data'),
]

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import auth
from django.urls import reverse


class Team(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200, blank=True, null=True)
    members = models.ManyToManyField(User)
    party = models.CharField(max_length=50, null=True, blank=True, default='Test')
    
    def __str__(self):
        return self.name

class Task(models.Model):
    created_by = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    status = models.CharField(max_length=20, choices=[
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed')
    ])
    incident_types = models.CharField(max_length=20, choices=[
        ('critical', 'Critical'),
        ('high', 'High'),
        ('medium', 'Medium')
    ], blank=True, null=True)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    assigned_team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_tasks')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('task_detail', kwargs={'id': self.id})

project/forms.py
from django import forms
from .models import *

class TeamForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = ['name', 'description', 'members']

project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponse
from datetime import timedelta
from django.utils import timezone
from django.db.models import F
from django.http import JsonResponse
from django.contrib.auth.models import Group
from .forms import *
from django.urls import reverse
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd
import urllib
import io
import os


def is_admin(user):
    return user.groups.filter(name='Admin').exists()

def is_team_lead(user):
    return user.groups.filter(name='Team_lead').exists()

def is_team_member(user):
    return user.groups.filter(name='Team_member').exists()

def has_admin_or_team_lead_permission(user):
    return user.is_authenticated and (is_admin(user) or is_team_lead(user))


def login_page(request):
    if request.user.is_authenticated:
        if is_admin(request.user):
            return redirect(reverse("admin_home"))
        elif is_team_lead(request.user):
            return redirect(reverse("team_lead_home"))
        elif is_team_member(request.user):
            return redirect(reverse("team_member_home"))
        else:
            return redirect(reverse("default_home"))
    return render(request, 'registration/login.html')


def admin_home(request):
    return render(request, 'admin_view/dashboard.html')


@login_required(login_url='/login')
# @user_passes_test(has_admin_or_team_lead_permission)
def home(request):
    if request.user.is_authenticated:
        if has_admin_or_team_lead_permission(request.user):
            assigned_tasks = Task.objects.filter(assigned_to=request.user).values()
            latest_assigned_task = Task.objects.filter(assigned_to=request.user).order_by('-id').first()
            deadline_list = Task.objects.filter(assigned_to=request.user).values_list('deadline', flat=True)

            closest_deadline = None
            current_date = timezone.now().date()
            for deadline in deadline_list:
                if closest_deadline is None or (deadline > current_date and deadline < closest_deadline):
                    closest_deadline = deadline

            task_with_closest_deadline = Task.objects.filter(assigned_to=request.user, deadline=closest_deadline).first()

            tasks_passed_deadline = assigned_tasks.filter(deadline__lt=current_date).count()

            out_of = Task.objects.all().count()

            active_tasks = Task.objects.filter(status='in_progress').count()

            completed_tasks = Task.objects.filter(status='completed').count()

            medium = Task.objects.filter(incident_types='medium').count()
            high = Task.objects.filter(incident_types='high').count()
            critical = Task.objects.filter(incident_types='critical').count()

            incident_type = {
                'medium': medium,
                'high': high,
                'critical': critical
            }

            user_roles = {
                'is_admin': is_admin(request.user),
                'is_team_lead': is_team_lead(request.user),
                'is_team_member': is_team_member(request.user),
            }

            pending_count = Task.objects.filter(status='pending').count()
            in_progress_count = Task.objects.filter(status='in_progress').count()
            completed_count = Task.objects.filter(status='completed').count()
            labels = ['Pending', 'In Progress', 'Completed']
            data = [pending_count, in_progress_count, completed_count]
            labels1 = ['Medium', 'High', 'Critical']
            data1 = [medium, high, critical]
        elif is_team_member(request.user):
            return redirect(reverse("TM_dashboard"))

    return render(request, 'base.html', {'assigned_tasks': assigned_tasks, 'latest_assigned_task': latest_assigned_task, 'deadline_alert': task_with_closest_deadline, 'user_roles': user_roles, 'tasks_passed_deadline': tasks_passed_deadline, 'active_tasks': active_tasks, 'completed_tasks': completed_tasks, 'out_of': out_of, 'incident_type': incident_type, 'labels': labels, 'data': data, 'labels1': labels1, 'data1': data1})


def user_activity_chart(request, user_id):
    user_activity = UserActivityLog.objects.filter(user_id=user_id)
    
    dates = [log.date for log in user_activity]
    activities = [log.activity for log in user_activity]

    # Create the chart
    plt.plot(dates, activities)
    plt.xlabel('Date')
    plt.ylabel('Activity')
    plt.title('User Activity Chart')
    
    # Save the chart to a file or render it directly in the template
    chart_path = 'path_to_save_chart/chart.png'  # Specify a path to save the chart
    plt.savefig(chart_path)

    return render(request, 'user_activity_chart.html', {'chart_path': chart_path})

def task_status_data(request):
    pending_count = Task.objects.filter(status='pending').count()
    in_progress_count = Task.objects.filter(status='in_progress').count()
    completed_count = Task.objects.filter(status='completed').count()
    
    # Create data for the chart
    labels = ['Pending', 'In Progress', 'Completed']
    data = [pending_count, in_progress_count, completed_count]
    
    
    return render(request, 'base.html', {'labels': labels, 'data': data})

def task_incident_data(request):
    medium = Task.objects.filter(incident_types='medium').count()
    high = Task.objects.filter(incident_types='high').count()
    critical = Task.objects.filter(incident_types='critical').count()
    
    # Create data for the chart
    labels = ['Medium', 'High', 'Critical']
    data = [medium, high, critical]
    
    return render(request, 'base.html', {'labels': label, 'data': data})

def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/task_view.html', {'tasks': tasks})

def task_detail(request, id):
    task = get_object_or_404(Task, id=id)
    return render(request, 'tasks/task_detail.html', {'task': task})

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'deadline', 'status', 'incident_types', 'assigned_to', 'assigned_team']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_create'] = True
        return context

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'status', 'incident_types']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_create'] = False
        return context

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        task = self.get_object()
        if self.request.user == task.created_by or self.request.user == task.assigned_to:
            return True
        return False

def add_team(request):
    # task = get_object_or_404(Task)

    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            # team.task = task
            team.save()
            response_data = {
                'team_id': team.pk,
                'status': 'success'
            }
            return JsonResponse(response_data)
    else:
        form = TeamForm()

    return render(request, 'tasks/add_team.html', {'form': form,})


def tm_dashboard(request):
    return render(request, 'TM_view/dashboard.html')

def team(request):
    teams = Team.objects.all()
    return render(request, 'tasks/team.html', {'teams': teams})

project/templates/tasks/add_team.html
{% load crispy_forms_tags %}

{% block content %}
<div class="Container" style="max-width: 460px;margin: auto; margin-top: 50px; padding: 0.5cm; border-radius: 10px; background-color: #e3f2fd; color: #0c0c0c;">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group" style="padding: 30px;">
      <legend style="font-size: 1.5em; font-weight: bold; color: #000000;">
        Create Team
      </legend>
      <div class="form-group" style="width: 90%;">
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>
      <div class="form-group" style="width: 90%;">
        {{ form.description.label_tag }}
        {{ form.description }}
      </div>
      <div class="form-group" style="width: 90%;">
        {{ form.task.label_tag }}
        {{ form.task }}
      </div>
      <div class="form-group" style="width: 90%;">
        {{ form.members.label_tag }}
        <select name="members" id="id_members" class="form-control">
            {% for choice in form.members.field.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group" style="width: 90%;">
        {{ form.members.label_tag }}
        <select name="members" id="id_members" class="form-control" multiple>
            {% for value, label in form.members.field.choices %}
                <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
        </select>
    </div>
    
    </fieldset>
    <div class="form-group">
      <button type="submit" style="background-color: #fff; color: #000000; border: none; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold;">
        Create Team
      </button>
    </div>
  </form>
</div>
{% endblock %}

project/templates/tasks/incident_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Incidents Chart</title>
</head>
<body>
    <h1>Task Incidents Chart</h1>
    <img src="{{ chart_path }}" alt="Task Incidents Chart">
</body>
</html>

project/templates/tasks/popup.html
{% if latest_assigned_task %}
<button type="button" class="btn btn-primary" id="liveToastBtn">Latest Task</button>

<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
  <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <img src="..." class="rounded me-2" alt="...">
      <strong class="me-auto">Latest Assigned Task</strong>
      <small>Deadline: {{ latest_assigned_task.deadline }}</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
        Title: {{ latest_assigned_task.title }}
    </div>
  </div>
</div>
{% endif %}

project/templates/tasks/status_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Status Chart</title>
</head>
<body>
    <h1>Task Incidents Chart</h1>
    <img src="{{ chart_path }}" alt="Task Status Chart">
</body>
</html>

project/templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="card" style="margin-top: 70px; margin-bottom: 50vh;">
        <h1 class="card-header">{{ task.title|capfirst }}</h1>
        <div class="card-body">
            <p class="card-text">Created By: {{ task.created_by|capfirst }}</p>
            <p class="card-text">Description: {{ task.description|lower|capfirst }}</p>
            <p class="card-text">Deadline Date: {{ task.deadline }}</p>
            <p class="card-text">Status: {{ task.status }}</p>
            <p class="card-text">Incident Type: {{task.incident_types|capfirst}}</p>
            <p class="card-text">Assigned To: {{ task.assigned_to }}</p>
        </div>
        <div class="card-footer">
            {% if task.created_by == user or task.assigned_to == user %}
            <a href="{% url 'task_update' pk=task.pk %}" class="btn btn-outline-primary">Update</a>
            <a href="{% url 'task-delete' pk=task.pk %}" class="btn btn-outline-danger">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

project/templates/tasks/task_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
  <form method="POST" enctype="multipart/form-data" class="container" id="form">
    {% csrf_token %}
    <fieldset class="form-group" style="padding: 30px;">
      <legend class="mb-4" style="font-size: 1.5em; font-weight: bold; color: #000000;">
        {% if is_create %}
        Create Task
        {% else %}
        Update Task
        {% endif %}
      </legend>
      <div class="form-group row">
        <label for="title" class="col-sm-4 col-form-label">Title:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-journal" aria-hidden="true"></i></div>
                {{ form.title }}
            </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="description" class="col-sm-4 col-form-label">Description:</label>
        <div class="col-sm-7">
            <div class="input-group">
                {{ form.description }}
            </div>
        </div>
      </div>
      {% if is_create %}
      <div class="form-group row">
        <label for="{{ form.deadline.id_for_label }}" class="col-sm-4" style="color: #000000;">Deadline:</label>
        <input type="date" name="{{ form.deadline.html_name }}" class="col-sm-7" id="{{ form.deadline.auto_id }}" value="{{ form.instance.deadline|default_if_none:'' }}">
      </div>
      <div class="form-group row">
        <label for="status" class="col-sm-4 col-form-label">Status:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-asterisk"></i></div>
                {{ form.status }}
            </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="incident_types" class="col-sm-4 col-form-label">Incident Type:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-cone"></i></div>
                {{ form.incident_types }}
            </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="assigned_to" class="col-sm-4 col-form-label">Assign To User:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-person-fill" aria-hidden="true"></i></div>
                {{ form.assigned_to }}
            </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="assigned_team" class="col-sm-4 col-form-label">Assign Team:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-people-fill" aria-hidden="true"></i></div>
                {{ form.assigned_team }}
            </div>
        </div>
      </div>
      {% else %}
      <div class="form-group row">
        <label for="incident_types" class="col-sm-4 col-form-label">Incident Type:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-cone"></i></div>
                {{ form.incident_types }}
            </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="status" class="col-sm-4 col-form-label">Status:</label>
        <div class="col-sm-7">
            <div class="input-group">
                <div class="input-group-addon"><i class="bi bi-asterisk" aria-hidden="true"></i></div>
                {{ form.status }}
            </div>
        </div>
      </div>
      {% endif %}
      <button type="submit" style="background-color: #fff; color: #000000; border: none; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-weight: bold;">
        {% if is_create %}
        Create Task
        {% else %}
        Update Task
        {% endif %}
      </button> 
    </div>
    </fieldset>
  </form>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
      $("#add-team-btn").click(function() {
          // Open a new window with the URL to your add team form
          var addTeamFormUrl = "{% url 'add_team' %}";
          var newWindow = window.open(addTeamFormUrl, "_blank", "width=600,height=400,top=100,left=100");

          // Listen for a message from the new window
          window.addEventListener('message', function(event) {
              var data = event.data;
              if (data.status === 'success') {
                  // Close the new window
                  newWindow.close();
              }
          });
      });
  });

  // Function to handle messages from child window
  window.addEventListener('message', function(event) {
      var data = event.data;
      if (data.status === 'success') {
          // Close the new window
          window.close();
      }
  });
</script>
<style>
  *{
    box-sizing: border-box;
    font-family: "Merriweather Sans", sans-serif;
  }

  #form{
    color: whitesmoke;
    background-color: #6499E9;
    border-radius: 5px;
    width: 600px;
    margin: auto;
    -webkit-box-shadow: -1px 3px 18px 0px rgba(0, 0, 0, 0.75);
    -moz-box-shadow: -1px 3px 18px 0px rgba(0, 0, 0, 0.75);
    box-shadow: -1px 3px 18px 0px rgba(0, 0, 0, 0.75); 
  }

  #form p{
    font-size: 0.9em;
  }

  #form label {
      color: black;
  }

  #form button{
    width: 100%;
    text-align: center;
    color: grey;
    background-color: whitesmoke;
    margin-top: 20px;
    border: 1px solid rgba(0, 0, 0, 0.4);
  }

  @media (max-width: 767px) {
      #form {
        width: auto;
        margin-left: 10px;
        margin-right: 10px;
        align-content: center;
        align-items: center;
      }
  }

</style>
{% endblock %}

project/templates/tasks/task_view.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row" style="margin-top: 70px; margin-bottom: 30px;">
        {% for task in tasks %}
        <div class="col-lg-4" style="margin-bottom: 30px;">
            <div class="card card-margin" style="max-height: 300px; min-height: 300px;">
                <div class="card-header no-border">
                    <h4 class="card-title">{{ task.title|capfirst }}</h4>
                </div>
                <div class="card-body">
                <p class="card-text">{{ task.description|capfirst }}</p>
                </div>
                <div class="card-footer no-border">
                    <a href="{% url 'task_detail' task.id %}" class="btn btn-outline">View Task Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div style="padding: 20px; margin-bottom: 50px; text-align: right;">
        <a href="{% url 'task-create' %}" class="btn btn-primary" style="text-decoration: none;">Add new Task</a>
    </div>
</div>

<style>
    body{
        background: #98e4ff2c;
        margin-top:20px;
    }

    .card-margin {
        margin-bottom: 1.875rem;
    }

    .card {
        border: 0;
        box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
        -webkit-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
        -moz-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
        -ms-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
    }
    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #ffffff;
        background-clip: border-box;
        border: 1px solid #e6e4e9;
        border-radius: 8px;
    }

    .card .card-header.no-border {
        border: 0;
    }
    .card .card-header {
        background: none;
        padding: 1 0.9375rem;
        font-weight: 500;
        display: flex;
        align-items: center;
        min-height: 50px;
    }
    .card-header:first-child {
        border-radius: calc(8px - 1px) calc(8px - 1px) 0 0;
    }

    .card .card-footer.no-border {
        border: 0;
    }

    .card .card-footer {
        background: none;
        padding: 1 0.9375rem;
        font-weight: 500;
        display: flex;
        min-height: 50px;
    }
</style>
{% endblock content %}

project/templates/tasks/team.html
{% extends 'base.html' %}
{% block content %}
<div style="height: 82vh;">
{% for team in teams %}
<li class="list-group" style="margin-top: 40px;">
    <div>
        <a href="{% url 'team' %}" class="list-group-item list-group-item-action">{{ team.name|capfirst }}</a>
    </div>
</li>
{% endfor %}
</div>

{% endblock content %}